language: node_js
node_js:
  - 14

install: npm install

# TODO: Run linting, tests
script: skip

before_deploy:
  - openssl aes-256-cbc -K $encrypted_84f7f15250c2_key -iv $encrypted_84f7f15250c2_iv -in deploy-rsa.enc -out deploy-rsa -d

deploy:
  - provider: script
    script: npm run deploy
