export default {
  USER: "USER",
  SESSION: "sess",
  EMAIL: "EMAIL",
  EMAIL_CONFIRMATION: "EMAIL_CONFIRMATION",
  DEBOT_CONFIRMATION: "DEBOT_CONFIRMATION",
  PENDING_WEBHOOKS: "PENDING_WEBHOOKS",
  VALID_WEBHOOKS: "VALID_WEBHOOKS",
  FAILED_WEBHOOKS: "FAILED_WEBHOOKS",
  DELIVERED_MESSAGE: "DELIVERED_MESSAGE",
  FAILED_MESSAGE: "FAILED_MESSAGE",
};
